config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'users/show'

  devise_for :users
  resources :users, :only => [:index, :show]

  root to: "windows#index"
  put 'api/:controller/:action'
  resources :requests
  resources :solutions
  resources :windows
end

app/models/request_solution.rb
class RequestSolution < ApplicationRecord
  belongs_to :request
  belongs_to :solution

  def self.find_by_shift(shift)
    joins(request: :shift).find_by(id: shift.id)
  end
end

app/controllers/request_solutions_controller.rb
class RequestSolutionsController < ApplicationController
  before_action :set_request_solution, only: [:show, :edit, :update, :destroy]

  # GET /request_solutions
  # GET /request_solutions.json
  def index
    @request_solutions = RequestSolution.all
  end

  # GET /request_solutions/1
  # GET /request_solutions/1.json
  def show
  end

  # GET /request_solutions/new
  def new
    @request_solution = RequestSolution.new
  end

  # GET /request_solutions/1/edit
  def edit
  end

  # POST /request_solutions
  # POST /request_solutions.json
  def create
    @request_solution = RequestSolution.new(request_solution_params)

    respond_to do |format|
      if @request_solution.save
        format.html { redirect_to @request_solution, notice: 'Request solution was successfully created.' }
        format.json { render :show, status: :created, location: @request_solution }
      else
        format.html { render :new }
        format.json { render json: @request_solution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /request_solutions/1
  # PATCH/PUT /request_solutions/1.json
  def update
    respond_to do |format|
      if @request_solution.update(request_solution_params)
        format.html { redirect_to @request_solution, notice: 'Request solution was successfully updated.' }
        format.json { render :show, status: :ok, location: @request_solution }
      else
        format.html { render :edit }
        format.json { render json: @request_solution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /request_solutions/1
  # DELETE /request_solutions/1.json
  def destroy
    @request_solution.destroy
    respond_to do |format|
      format.html { redirect_to request_solutions_url, notice: 'Request solution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request_solution
      @request_solution = RequestSolution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_solution_params
      params.fetch(:request_solution, {})
    end
end

app/helpers/request_solutions_helper.rb
module RequestSolutionsHelper
end

app/views/request_solutions/_form.html.erb
<%= form_for(request_solution) do |f| %>
  <% if request_solution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request_solution.errors.count, "error") %> prohibited this request_solution from being saved:</h2>

      <ul>
      <% request_solution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/request_solutions/edit.html.erb
<h1>Editing Request Solution</h1>

<%= render 'form', request_solution: @request_solution %>

<%= link_to 'Show', @request_solution %> |
<%= link_to 'Back', request_solutions_path %>

app/views/request_solutions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Request Solutions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @request_solutions.each do |request_solution| %>
      <tr>
        <td><%= link_to 'Show', request_solution %></td>
        <td><%= link_to 'Edit', edit_request_solution_path(request_solution) %></td>
        <td><%= link_to 'Destroy', request_solution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request Solution', new_request_solution_path %>

app/views/request_solutions/new.html.erb
<h1>New Request Solution</h1>

<%= render 'form', request_solution: @request_solution %>

<%= link_to 'Back', request_solutions_path %>

app/views/request_solutions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_request_solution_path(@request_solution) %> |
<%= link_to 'Back', request_solutions_path %>