config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'users/show'

  devise_for :users
  resources :users, :only => [:index, :show]

  root to: "windows#index"
  put 'api/:controller/:action'
  resources :requests
  resources :solutions
  resources :windows
end

app/models/solution.rb
class Solution < ApplicationRecord
  belongs_to :user
  belongs_to :window
  has_many :request_solutions
  has_many :requests, through: :request_solutions

  def score
    # 加味する要素
    # userのpoint
    # そのshiftの人気
    # eagerness
    
    score = requests.sum{|request| 
      request.score_by_point + request.shift.score_by_popularity + request.eagerness.to_f/4.to_f
    }
    score = (score / requests.count.to_f * 100 )
    user_ids = []
    requests.each do |request|
      user_ids << request.user_id
    end
    # 3回入った人がいれば3というように、一番シフトに入った人の回数を求める。
    duplication_count = user_ids.select{|id| user_ids.count(id) > 1 }.uniq.map{|id| user_ids.count(id)}.max
    score /= duplication_count.to_f
    score.round(2)
  end

  def default_request_id_for_select_tag(shift)
    unless new_record?
      request_solutions.find_by_shift(shift)&.request&.id
    end
  end

  def self.greatest
    all.sort_by { |solution| - solution.score }.first
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  before_action :set_solution, only: [:show, :edit, :update, :destroy]
  before_action :set_window, only: [:index, :new]

  # GET /solutions
  # GET /solutions.json
  def index
    @solutions = Solution.where(window: @window).sort_by { |solution| - solution.score }
  end

  # GET /solutions/1
  # GET /solutions/1.json
  def show
  end

  # GET /solutions/new
  def new
    if params[:copy_from].present? && Solution.find(params[:copy_from])&.user == current_user
      @solution = Solution.find(params[:copy_from])
    else
      @solution = Solution.new
    end
    @shifts = Shift.where(window: @window).group_by{|s| s.start.strftime("%Y-%m-%d")}
  end

  # GET /solutions/1/edit
  def edit
  end

  # POST /solutions
  # POST /solutions.json
  def create
    # params[:shifts]は、Shiftのid => Requestのid のハッシュ
    shift = Shift.find(params[:shifts].first.first.to_i)
    solution = current_user.solutions.create(window: shift.window)
    request_solutions = params[:shifts].map{|_, request_id| solution.request_solutions.build(request_id: request_id.to_i) }

    if RequestSolution.import request_solutions
      redirect_to controller: :solutions, action: 'index', notice: 'シフトの解決案を提出しました。', window_id: solution.window.id
    end
  end

  # PATCH/PUT /solutions/1
  # PATCH/PUT /solutions/1.json
  def update
    respond_to do |format|
      if @solution.update(solution_params)
        format.html { redirect_to @solution, notice: 'Solution was successfully updated.' }
        format.json { render :show, status: :ok, location: @solution }
      else
        format.html { render :edit }
        format.json { render json: @solution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /solutions/1
  # DELETE /solutions/1.json
  def destroy
    @solution.destroy
    respond_to do |format|
      format.html { redirect_to solutions_url, notice: 'Solution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_solution
      @solution = Solution.find(params[:id])
    end
    
    def set_window
      @window = Window.find(params[:window_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def solution_params
      params.fetch(:solution, {})
    end
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/views/solutions/_form.html.erb
<%= form_for @solution.dup do |f| %>
  <% if solution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(solution.errors.count, "error") %> prohibited this solution from being saved:</h2>

      <ul>
      <% solution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.submit 'シフトを提出', :class => 'btn btn-primary' %>
  </div>

  <div class='timetable'>
      <% @shifts.each do |day, shiftday| %>
        <div class='day'>
        <%= day %>
        <% shiftday.each do |shift| %>
        <div class='box'><%= shift.start.strftime('%H:%M') %> - <%= shift.end.strftime('%H:%M') %>
        <%= select_tag(
          "shifts[#{shift.id}]",
          options_for_select(
            shift.requests.for_select_tag,
            @solution.default_request_id_for_select_tag(shift)
          ))
        %>
        </div>
      <% end %>
      </div>
      <% end %>
  </div>
  <%= javascript_tag do %>
    req_user = {
      <% @shifts.each do |day, shiftday| %>
        <% shiftday.each do |shift| %>
          <% shift.requests.each do |req| %>
            <%= req.id %>: <%= req.user.id %>,
          <% end %>
        <% end %>
      <% end %>
    }
    recolor = function () {
      k = $('select').map(function(){ return req_user[$(this).val()] })
      bucket = []
      for (i = 0; i < k.length; i++) {
        bucket[k[i]] = bucket[k[i]] || 0
        bucket[k[i]] += 1
      }
      table = []
      for (i = 0; i < k.length; i++) {
        if (bucket[k[i]] != 1) {
          table.push(i);
        }
      }
      $('.box').css('color', 'black')
      for (i = 0; i < table.length; i++) {
        $($('.box')[table[i]]).css('color', 'red')
      }
    };
    recolor();
    $('select').change(recolor);
  <% end %>
<% end %>

app/views/solutions/index.html.erb
<div class="row">
<h1 class="col-xl-10 col-lg-10 col-md-10 col-sm-10 col-xs-10">解決案一覧  <%= @solutions.first.window.period if @solultions %></h1>
<%= link_to 'New Solution', new_solution_path(window_id: @window.id),  {class: "col-xl-2 col-lg-2 col-md-2 col-sm-2 col-xs-2  btn btn-primary new-button"}%>
</div>
<div class="row">
<p><%= @solutions.first.window.message if @solultions %></p>

</div>
<% if @solutions.length != 0 %>
<div class="row">
<table class="table table-striped">
  <thead>
    <tr>
      <th class="col-xl-2 col-lg-2 col-md-2 col-sm-2 col-xs-2">氏名</th>
      <th class="col-xl-2 col-lg-2 col-md-2 col-sm-2 col-xs-2">解決案の得点</th>
      <th class="col-xl-2 col-lg-2 col-md-2 col-sm-2 col-xs-2">提出日時</th>
      <th class="col-xl-2 col-lg-2 col-md-2 col-sm-2 col-xs-2">回答をコピーして再提出</th>
    </tr>
  </thead>

  <tbody>
    <% @solutions.each do |solution| %>
      <% if solution.user == current_user %>
      <tr class="info">
      <% else %>
      <tr>
      <% end %>
        <td>
        <%= link_to solution.user.name, user_path(solution.user) %></td>
        <td><%= solution.score %></td>
        <td><%= solution.created_at.strftime('%Y-%m-%d %H:%M') %></td>
        <td><% if current_user == solution.user then %><%= link_to 'Copy', new_solution_path(window_id: solution.window.id, copy_from: solution.id) %><% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>
<% else %>
<p>解決案がありません。解決案を投稿してください。<p>
<% end %>

app/views/solutions/new.html.erb
<%= render 'form', solution: @solution %>
<h3>Hint:</h3>
<ul>
  <% User.all.sort{|u, v| u.counts_in_window(@window) <=> v.counts_in_window(@window)}[0..10].each {|u| %>
    <li>
      <%= u.name %>
      <% u.in_window(@window).each {|r| %>
        <%= r.shift.start.strftime('%m/%d %H:%M') %>,
      <% } %>
    </li>
<% } %>
</ul>

<script type='text/javascript'>
function change_color(){
  $('.box').each(function(i, box){
    var selected_request_id = $(box).children().first().val();
    var selected_option = $(box).children().first().children().filter((ind, elem) => elem.value === selected_request_id ).first();
    var tiredness = parseInt(selected_option.text().split('/')[1].match(/\d+/)[0]);
    var eagerness = parseInt(selected_option.text().split('/')[2].match(/\d+/)[0]);
    var virtual_score = Math.exp(0 - tiredness) + Math.exp(0 - $(box).length) + (eagerness/4.0);

    var redness = Math.round(255 * Math.exp(0 - virtual_score));
    console.log(redness);
    $(box).css('background-color', `rgb(255, ${255 - redness} , 255)`);
  });
};
change_color();
$('select').each((ind, select) => {
  select.addEventListener('change', change_color);
});
</script>

app/views/solutions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_solution_path(@solution) %> |
<%= link_to 'Back', solutions_path %>